(define (fast-expt b n)
  (define (inner_expt a b n)
    (cond ((= n 0) a)
          ((even? n) (inner_expt a (* b b) (/ n 2)))
          (else (inner_expt (* a b) b (- n 1)))
    )
  )
  (inner_expt 1 b n)
)
