(define (expmod base exp m)
  (cond ((= exp 0 ) 1)
        ((even? exp)
         (remainder (square (expmod base (/ exp 2) m))
                    m)
        )
        (else
         (remainder (* base (expmod base (- exp 1) m))
                    m)
        )
  )
)

(define (fermat-test n)
  (define (try-it a)
    (= (expmod a n n) a))
  (try-it (+ 1 (random (- n 1))))
)

(define (fast-prime? n times)
  (cond ((= times 0) true)
        ((fermat-test n) (fast-prime? n (- times 1)))
        (else false)
  )
)

(define (timed-prime-test n)
  (newline)
  (display n)
  (start-prime-test n (runtime))
)

(define (start-prime-test n start-time)
  (if (fast-prime? n 1000)
      (report-prime (- (runtime) start-time))
  )
)

(define (report-prime elapsed-time)
  (display " *** ")
  (display elapsed-time)
)

(define (search-for-primes start)
  (define (next n)
    (cond ((= (remainder n 2) 0) (+ n 1))
          (else (+ n 2))
    )
  )
  (cond ((fast-prime? start 1000) start)
        (else (search-for-primes (next start)))
  )
)

(timed-prime-test (search-for-primes 1000000000))
(timed-prime-test (search-for-primes 1000000000000))
(timed-prime-test (search-for-primes 1000000000000000))
(timed-prime-test (search-for-primes 1000000000000000000))
(timed-prime-test (search-for-primes 1000000000000000000000))
