(define (double a) (* a 2))
(define (halve a) 
  (if (even? a) (/ a 2) a)
)

(define (fast-mul a b)
  (define (reduce a)
    (if (< a 0) (+ a 1)
      (- a 1)
    )
  )
  (define (inner_mul a b c)
    (cond ((= (abs a) 1 ) (* a (+ b c)))
          ((even? a) (inner_mul (halve a) (double b) c))
          (else (inner_mul (reduce a) b (+ c b)))
    )
  )
  (inner_mul a b 0)
)
