(define (smallest-divisor n)
  (find-divisor n 2)
)

(define (find-divisor n test-divisor)
  (cond ((> (square test-divisor) n) n)
        ((divides? test-divisor n) test-divisor)
        (else (find-divisor n (+ test-divisor 1)))
  )
)

(define (divides? a b)
  (= (remainder b a) 0)
)

(define (prime? n)
  (= n (smallest-divisor n))
)

(define (timed-prime-test n)
  (newline)
  (display n)
  (start-prime-test n (runtime))
)

(define (start-prime-test n start-time)
  (if (prime? n)
      (report-prime (- (runtime) start-time))
  )
)

(define (report-prime elapsed-time)
  (display " *** ")
  (display elapsed-time)
)

(define (search-for-primes start)
  (define (next n)
    (cond ((= (remainder n 2) 0) (+ n 1))
          (else (+ n 2))
    )
  )
  (cond ((prime? start) start)
        (else (search-for-primes (next start)))
  )
)

(timed-prime-test (search-for-primes 1000000000))
(timed-prime-test (search-for-primes 1000000000000))
(timed-prime-test (search-for-primes 1000000000000000))

