(define (expmod base exp m)
  (define (remainder-square-signal a b)
    (define return (remainder (square a) b))
    (if (and (not (or (= a 1)  
                      (= a (- b 1))))
             (= return 1)) 
        0
        return))
  (cond ((= exp 0 ) 1)
        ((even? exp)
         (remainder-square-signal (expmod base (/ exp 2) m) 
                                  m))
        (else
         (remainder (* base (expmod base (- exp 1) m))
                    m))))

(define (miller-rabin-test n)
  (define (try-it a)
    (= (expmod a (- n 1) n) 1)
  )
  (try-it (+ 1 (random (- n 1))))
)

(define (prime? n times)
  (cond ((= times 0) true)
        ((miller-rabin-test n) (prime? n (- times 1)))
        (else false))
)

(define (report n)
  (display n)
  (if (prime? n 1000) (display " is prime.")
                      (display " is not prime.")
  )
  (newline)
)

(newline)
(report 7)
(report 1009)
(report 561)
(report 1105)
(report 1729)
(report 2465)
(report 2821)
(report 6601)
